import User from "../models/userModel.js";
import Ticket from "../models/ticketModel.js";

export const getTickets = async (req, res) => {
  // Get user using the id and JWT
  const user = await User.findById(req.user.id);

  if (!user) {
    res.status(401);
    throw new Error("User not found");
  }

  const tickets = await Ticket.find({ user: req.user._id })
    .sort({ createdAt: -1 }) 
    .populate("user", "name email");

  res.status(200).json(tickets);
};

export const getTicket = async (req, res) => {
  const user = await User.findById(req.user.id);

  if (!user) {
    res.status(401);
    throw new Error("User not found");
  }

  const ticket = await Ticket.findById(req.params.id).populate("user", "id");

  if (!ticket) {
    res.status(404);
    throw new Error("Ticket not found");
  }

  // Check if ticket belongs to user or if user is admin
  if (ticket.user._id.toString() !== req.user.id && !req.user.isAdmin) {
    res.status(401);
    throw new Error("Not authorized");
  }

  res.status(200).json(ticket);
};

export const createTicket = async (req, res) => {
  const {
    category,
    description,
    priority,
    department,
    assignedTo,
    file,
    leaveDays,
  } = req.body;

  // Validation (unchanged)
  if (!category || !description || !department) {
    res.status(400);
    throw new Error("Please provide category, description, and department");
  }

  if (!["HR", "IT"].includes(department)) {
    res.status(400);
    throw new Error("Department must be either HR or IT");
  }

  if (
    priority &&
    !["4-Low", "3-Moderate", "2-High", "1-Critical"].includes(priority)
  ) {
    res.status(400);
    throw new Error("Invalid priority level");
  }

  const user = await User.findById(req.user.id);
  if (!user) {
    res.status(401);
    throw new Error("User not found");
  }

  // Create ticket - ticketNumber will be auto-generated by pre-save hook
  const ticket = new Ticket({
    user: req.user.id,
    name: req.user.name,
    category,
    description,
    status: "open",
    priority: priority || "4-Low",
    assignedTo: assignedTo || "Not Assigned",
    file,
    department,
    leaveDays,
  });

  await ticket.save();
  res.status(201).json(ticket);
};

export const deleteTicket = async (req, res) => {
  const user = await User.findById(req.user.id);

  if (!user) {
    res.status(401);
    throw new Error("User not found");
  }

  const ticket = await Ticket.findById(req.params.id);

  if (!ticket) {
    res.status(404);
    throw new Error("Ticket not found");
  }

  await ticket.deleteOne();

  res.status(200).json({ success: true });
};

export const updateTicket = async (req, res) => {
  const user = await User.findById(req.user.id);

  if (!user) {
    res.status(401);
    throw new Error("User not found");
  }

  const ticket = await Ticket.findById(req.params.id);

  if (!ticket) {
    res.status(404);
    throw new Error("Ticket not found");
  }

  // Validate status if provided
  if (
    req.body.status &&
    !["open", "closed", "In Progress", "Approved", "Rejected"].includes(
      req.body.status,
    )
  ) {
    res.status(400);
    throw new Error("Invalid status value");
  }

  // Validate priority if provided
  if (
    req.body.priority &&
    !["4-Low", "3-Moderate", "2-High", "1-Critical"].includes(req.body.priority)
  ) {
    res.status(400);
    throw new Error("Invalid priority value");
  }

  // Validate department if provided
  if (req.body.department && !["HR", "IT"].includes(req.body.department)) {
    res.status(400);
    throw new Error("Department must be either HR or IT");
  }

  const updatedTicket = await Ticket.findByIdAndUpdate(
    req.params.id,
    req.body,
    { new: true, runValidators: true },
  ).populate("user", "name email");

  res.status(200).json(updatedTicket);
};

export const viewAllTickets = async (req, res) => {
  const tickets = await Ticket.find()
    .sort({ createdAt: -1 })
    .populate("user", "name email");
  res.status(200).json(tickets);
};

export const viewOpenTickets = async (req, res) => {
  const tickets = await Ticket.find({
    status: { $in: ["open", "In Progress"] },
  })
    .sort({ createdAt: -1 })
    .populate("user", "name email");
  res.status(200).json(tickets);
};

export const viewClosedTickets = async (req, res) => {
  const tickets = await Ticket.find({ status: "closed" })
    .sort({ createdAt: -1 })
    .populate("user", "name email");
  res.status(200).json(tickets);
};

export const viewTicketsByDepartment = async (req, res) => {
  const { dept } = req.params;

  if (!["HR", "IT"].includes(dept)) {
    res.status(400);
    throw new Error("Invalid department");
  }

  const tickets = await Ticket.find({ department: dept })
    .sort({ createdAt: -1 })
    .populate("user", "name email");
  res.status(200).json(tickets);
};

export const viewTicketsByPriority = async (req, res) => {
  const { level } = req.params;

  if (!["4-Low", "3-Moderate", "2-High", "1-Critical"].includes(level)) {
    res.status(400);
    throw new Error("Invalid priority level");
  }

  const tickets = await Ticket.find({ priority: level })
    .sort({ createdAt: -1 })
    .populate("user", "name email");
  res.status(200).json(tickets);
} ;

export const viewTicketsByCategory = async (req, res) => {
  const { category } = req.params;

  const tickets = await Ticket.find({ category })
    .sort({ createdAt: -1 })
    .populate("user", "name email");
  res.status(200).json(tickets);
};
