import asyncHandler from "express-async-handler";
import User from "../models/userModel";
import Ticket from "../models/ticketModel";

// @desc    Get user tickets
// @route   GET /api/tickets
// @access  Private
export const getTickets = asyncHandler(async (req, res) => {
  try {
    const user = await User.findById(req.user.id);
    if (!user) {
      return res.status(401).json({
        success: true,
        message: "User not found",
      });
    }

    const tickets = await Ticket.find({ user: req.user._id })
      .sort({ createdAt: -1 }) // Sort tickets from new to old
      .populate("user", "name email");

    res.status(200).json({
      success: true,
      message: "Fetch Tickets",
      tickets,
    });
  } catch (error) {
    console.error(error.message);
    req.status(500).json({
      success: true,
      message: "Internal Server Error",
    });
  }
});

// @desc    Get user ticket
// @route   GET /api/tickets/:id
// @access  Private
export const getTicket = asyncHandler(async (req, res) => {
  try {
    const user = await User.findById(req.user.id);

    if (!user) {
      return res.status(401).json({
        success: false,
        message: "User not found",
      });
    }

    const ticket = await Ticket.findById(req.params.id).populate("user", "id");

    if (!ticket) {
      return res.status(404).json({
        success: false,
        message: "Ticket not found",
      });
    }

    // Check if ticket belongs to user or if user is admin
    if (ticket.user._id.toString() !== req.user.id && !req.user.isAdmin) {
      return res.status(401).json({
        success: false,
        message: "Not authorized",
      });
    }

    res.status(200).json({
      success: false,
      message: "Fetch Ticket",
      ticket,
    });
  } catch (error) {
    console.error(error.message);
    req.status(500).json({
      success: false,
      message: "Internal Server Error",
    });
  }
});

// @desc    Create new ticket
// @route   POST /api/tickets
// @access  Private
export const createTicket = asyncHandler(async (req, res) => {
  try {
    const {
      category,
      description,
      priority,
      department,
      assignedTo,
      file,
      leaveDays,
    } = req.body;

    // Validation (unchanged)
    if (!category || !description || !department) {
      return res.status(400).json({
        success: true,
        message: "Please provide category, description, and department",
      });
    }

    if (!["HR", "IT"].includes(department)) {
      return res.status(400).json({
        success: true,
        message: "Department must be either HR or IT",
      });
    }

    if (
      priority &&
      !["4-Low", "3-Moderate", "2-High", "1-Critical"].includes(priority)
    ) {
      return res.status(400).json({
        success: true,
        message: "Invalid priority level",
      });
    }

    const user = await User.findById(req.user.id);
    if (!user) {
      return res.status(401).json({
        success: true,
        message: "User not found",
      });
    }

    // Create ticket - ticketNumber will be auto-generated by pre-save hook
    const ticket = new Ticket({
      user: req.user.id,
      name: req.user.name,
      category,
      description,
      status: "open",
      priority: priority || "4-Low",
      assignedTo: assignedTo || "Not Assigned",
      file,
      department,
      leaveDays,
    });

    await ticket.save();

    res.status(201).json({
      status: true,
      message: "Create ticket successfully",
      ticket,
    });
  } catch (error) {
    console.error(error.message);
    req.status(500).json({
      status: false,
      message: "Internal Server Error",
    });
  }
});

// @desc    Delete ticket
// @route   DELETE /api/tickets/:id
// @access  Private
export const deleteTicket = asyncHandler(async (req, res) => {
  try {
    const user = await User.findById(req.user.id);

    if (!user) {
      return res.status(401).json({
        success: false,
        message: "User not found",
      });
    }

    const ticket = await Ticket.findById(req.params.id);

    if (!ticket) {
      return res.status(404).json({
        success: false,
        message: "Ticket not found",
      });
    }

    await ticket.deleteOne();

    res.status(200).json({
      success: true,
      message: "Deleted ticket",
    });
  } catch (error) {
    console.error(error.message);
    req.status(500).json({
      success: true,
      message: "Internal Server Error",
    });
  }
});

// @desc    Update ticket
// @route   PUT /api/tickets/:id
// @access  Private
export const updateTicket = asyncHandler(async (req, res) => {
  try {
    const user = await User.findById(req.user.id);

    if (!user) {
      return res.status(401).json({
        success: true,
        message: "User not found",
      });
    }

    const ticket = await Ticket.findById(req.params.id);

    if (!ticket) {
      return res.status(404).json({
        success: false,
        message: "Ticket not found",
      });
    }

    // Validate status if provided
    if (
      req.body.status &&
      !["open", "closed", "In Progress", "Approved", "Rejected"].includes(
        req.body.status,
      )
    ) {
      return res.status(400).json({
        success: false,
        message: "Invalid status value",
      });
    }

    // Validate priority if provided
    if (
      req.body.priority &&
      !["4-Low", "3-Moderate", "2-High", "1-Critical"].includes(
        req.body.priority,
      )
    ) {
      return res.status(400).json({
        success: false,
        message: "Invalid priority value",
      });
    }

    // Validate department if provided
    if (req.body.department && !["HR", "IT"].includes(req.body.department)) {
      return res.status(400).json({
        success: false,
        message: "Department must be either HR or IT",
      });
    }

    const updatedTicket = await Ticket.findByIdAndUpdate(
      req.params.id,
      req.body,
      { new: true, runValidators: true },
    ).populate("user", "name email");

    res.status(200).json({
      success: true,
      message: "Update ticket successfully",
      updatedTicket,
    });
  } catch (error) {
    console.error(error.message);
    res.status(500).json({
      success: false,
      message: "Internal Server Error",
    });
  }
});

// @desc    View all tickets
// @route   GET /api/tickets/all
// @access  Private (Admin)
export const viewAllTickets = asyncHandler(async (req, res) => {
  try {
    const tickets = await Ticket.find()
      .sort({ createdAt: -1 })
      .populate("user", "name email");

    res.status(200).json({
      status: false,
      message: "Fetch all tickets",
      tickets,
    });
  } catch (error) {
    console.error(error.message);
    res.status(500).json({
      success: false,
      message: "Internal Server Error",
    });
  }
});

// @desc    View open tickets
// @route   GET /api/tickets/open
// @access  Private
export const viewOpenTickets = asyncHandler(async (req, res) => {
  try {
    const tickets = await Ticket.find({
      status: { $in: ["open", "In Progress"] },
    })
      .sort({ createdAt: -1 })
      .populate("user", "name email");

    res.status(200).json({
      succes: true,
      message: "View all open tickets",
      tickets,
    });
  } catch (error) {
    console.error(error.message);
    req.status(500).json({
      success: false,
      message: "Internal Server Error",
    });
  }
});

// @desc    View closed tickets
// @route   GET /api/tickets/closed
// @access  Private
export const viewClosedTickets = asyncHandler(async (req, res) => {
  try {
    const tickets = await Ticket.find({ status: "closed" })
      .sort({ createdAt: -1 })
      .populate("user", "name email");
    res.status(200).json({
      success: true,
      message: "View all closed tickets",
      tickets,
    });
  } catch (error) {
    console.error(error.message);
    req.status(500).json({
      success: false,
      message: "Internal Server Error",
    });
  }
});

// @desc    View tickets by department
// @route   GET /api/tickets/department/:dept
// @access  Private
export const viewTicketsByDepartment = asyncHandler(async (req, res) => {

  try {
      const { dept } = req.params;

  if (!["HR", "IT"].includes(dept)) {
    return res.status(400).json({
      success: false,
      message: "Invalid Department"
    });
  }

  const tickets = await Ticket.find({ department: dept })
    .sort({ createdAt: -1 })
    .populate("user", "name email");
    
  res.status(200).json({
    succes: true,
    message: "View tickets by deparment",
    tickets
  });
    
  } catch (error) {
    console.error(error.message);
    res.status(500).json({
      success: false,
      message: "Internal Server Error"
    })
    
  }
});

// @desc    View tickets by priority
// @route   GET /api/tickets/priority/:level
// @access  Private
export const viewTicketsByPriority = asyncHandler(async (req, res) => {
  try {
    const { level } = req.params;

    if (!["4-Low", "3-Moderate", "2-High", "1-Critical"].includes(level)) {
      return res.status(400).json({
        succes: true,
        message: "Invalid priority level",
      });
    }

    const tickets = await Ticket.find({ priority: level })
      .sort({ createdAt: -1 })
      .populate("user", "name email");

    res.status(200).json({
      succes: true,
      message: "View ticket by priority",
      tickets,
    });
  } catch (error) {
    console.error(error.message);
    req.status(500).json({
      success: false,
      message: "Internal Server Error",
    });
  }
});

export const viewTicketsByCategory = asyncHandler(async (req, res) => {
  try {
    const { category } = req.params;

    const tickets = await Ticket.find({ category })
      .sort({ createdAt: -1 })
      .populate("user", "name email");

    res.status(200).json({
      success: true,
      message: "View tickets by category",
      tickets,
    });
  } catch (error) {
    console.error(error.message);
    req.status(500).json({
      success: false,
      message: "Internal Server Error",
    });
  }
});
